/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#707881",
        "inverse-primary": "#93ccff",
        "on-background": "#111c2d",
        "on-error": "#ffffff",
        "on-primary-container": "#fdfcff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#d8e3fb",
        "surface-container-low": "#f0f3ff",
        "secondary-fixed": "#6bff8f",
        "on-tertiary-fixed": "#2a1700",
        "surface-bright": "#f9f9ff",
        "on-secondary": "#ffffff",
        "secondary-container": "#6bff8f",
        "secondary-fixed-dim": "#4ae176",
        "secondary": "#006e2f",
        "surface-tint": "#006398",
        "primary-fixed-dim": "#93ccff",
        "inverse-surface": "#263143",
        "on-surface-variant": "#3f4850",
        "surface-container": "#e7eeff",
        "primary-container": "#007bb9",
        "tertiary-container": "#a36700",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "surface": "#f9f9ff",
        "tertiary": "#825100",
        "outline-variant": "#bfc7d2",
        "tertiary-fixed": "#ffddb8",
        "on-secondary-container": "#007432",
        "surface-container-high": "#dee8ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#d8e3fb",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002109",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed-dim": "#ffb95f",
        "primary": "#006194",
        "surface-dim": "#cfdaf2",
        "on-primary": "#ffffff",
        "primary-fixed": "#cce5ff",
        "on-tertiary": "#ffffff",
        "on-surface": "#111c2d",
        "on-primary-fixed-variant": "#004b73",
        "on-primary-fixed": "#001d31",
        "on-secondary-fixed-variant": "#005321",
        "inverse-on-surface": "#ecf1ff",
        "background": "#f9f9ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin": "24px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "16px",
        "sm": "8px",
        "base": "4px",
        "xs": "4px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "data-mono": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "data-mono": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-md": ["20px", {"lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
